[
 {
  SERVER_ADDRESS:"https://wallet.unikbase.dev",
  BASIC_AUTH:"appclient:8O6vbFH431W7",
  KEYCLOAK_URL:"https://wallet.unikbase.dev/auth",
  UNIVERSAL_LINK:"link.unikbase.dev"
},
 { 
  SERVER_ADDRESS:"https://k8s.unikbase.dev",
  BASIC_AUTH:"appclient:8O6vbFH431W7",
  KEYCLOAK_URL:"https://k8s.unikbase.dev/auth",
  UNIVERSAL_LINK:"link.unikbase.dev"
},
]
